:toc:
:toc-title: Contents
:toclevels: 4
:source-highlighter: highlightjs
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
ifndef::env-github[]
:imagesdir: ./images/
:icons: font
endif::[]


= Python SonarQube Client

A python client for SonarQube 

NOTE: This project is still a WIP and will have missing features


== Installation

----
pip install git+https://github.com/rage28/py-sonarqube-client
----


== Compatibility

* This package is compatible Python versions 3.6+
* Tested with SonarQube EE v7.9


== Usage

The API handler is easy to use, you just need to initialize it with the
connection parameters (by default *localhost* on port *9000* without
authentication) and use any of the methods to get the required information or
create rules.


=== Example getting projects with coverage and issues metrics

[source, python]
----
from sonarqube import SonarQubeAPI

h = SonarQubeClient(user='admin', password='admin')
for project in h.projects:
    # do something with project data...
----

Since the actual response data from SonarQube server is usually paged, all
methods return generators to optimize memory as well retrieval performance of
the first items.

Sonar authentication tokens can also be used in place of username and password,
which is particularly useful when accessing the SonarQube API from a CI server,
as tokens can easily be revoked in the event of unintended exposure::

[source, python]
----
h = SonarQubeClient(token='<TOKEN>')
----
